language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
 - npm lint
 - npm run build
 - npm run generate

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: './out/'
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
