language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

script:
 - npm test
 - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: './build/'
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
