language: node_js
node_js:
  - lts/*

cache: npm

script:
  - npm run lint
  - npm run test
  # - npm run build-storybook
  - npm run build
  - npm run generate

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: './dist/'
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
