language: node_js
node_js:
  - '4.3'
env:
  global:
    - GH_REF: github.com/FBerthelot/tribu-web-prez.git
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run deploy; fi