name: Continous Integration and Delivery

on:
  push:
    branches:
      - master
env:
  NODE_VERSION: '16.17.1'
  NEXT_ENV_SHEETDB_URL: ${{ secrets.NEXT_ENV_SHEETDB_URL }}
  NUXT_ENV_MAPS_URL: ${{ secrets.NUXT_ENV_MAPS_URL }}
  NUXT_ENV_SLACK_URL: ${{ secrets.NUXT_ENV_SLACK_URL }}

permissions:
  contents: write

jobs:
  build-test-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install Node.js 🌍
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build
          npm run generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
